
events:
  e_init:                     "folder e_init_m,e_init_d"
  # Init: Marry
  e_init_m:                   "folder e_init_m_1,e_init_m_2"
  e_init_m_1:                 "folder e_so_m_saspaa,e_so_m_PiT_MiN,e_so_m_BirgitP,e_so_m_tyloreo,e_so_m_bigbabie,e_so_m_lepicah,e_so_m_LiquidSponge"
  e_init_m_2:                 "folder e_so_m_SlorpGaming,e_so_m_omg_beebo,e_so_m_whimsybun,e_so_m_SmackDan,e_so_m_Blomstermoy,e_so_m_Haugland"
  e_so_m_saspaa:              "objective add o_marrysaspaa"
  e_so_m_PiT_MiN:             "objective add o_marryPiT_MiN"
  e_so_m_BirgitP:             "objective add o_marryBirgitP"
  e_so_m_tyloreo:             "objective add o_marrytyloreo"
  e_so_m_bigbabie:            "objective add o_marrybigbabie"
  e_so_m_lepicah:             "objective add o_marrylepicah"
  e_so_m_LiquidSponge:        "objective add o_marryLiquidSponge"
  e_so_m_SlorpGaming:         "objective add o_marrySlorpGaming"
  e_so_m_omg_beebo:           "objective add o_marryomg_beebo"
  e_so_m_whimsybun:           "objective add o_marrywhimsybun"
  e_so_m_SmackDan:            "objective add o_marrySmackDan"
  e_so_m_Blomstermoy:         "objective add o_marryBlomstermoy"
  e_so_m_Haugland:            "objective add o_marryHaugland"
  # Init: Divorce
  e_init_d:                   "folder e_init_d_1,e_init_d_2"
  e_init_d_1:                 "folder e_so_d_saspaa,e_so_d_PiT_MiN,e_so_d_BirgitP,e_so_d_tyloreo,e_so_d_bigbabie,e_so_d_lepicah,e_so_d_LiquidSponge"
  e_init_d_2:                 "folder e_so_d_SlorpGaming,e_so_d_omg_beebo,e_so_d_whimsybun,e_so_d_SmackDan,e_so_d_Blomstermoy,e_so_d_Haugland"
  e_so_d_saspaa:              "objective add o_divorcesaspaa"
  e_so_d_PiT_MiN:             "objective add o_divorcePiT_MiN"
  e_so_d_BirgitP:             "objective add o_divorceBirgitP"
  e_so_d_tyloreo:             "objective add o_divorcetyloreo"
  e_so_d_bigbabie:            "objective add o_divorcebigbabie"
  e_so_d_lepicah:             "objective add o_divorcelepicah"
  e_so_d_LiquidSponge:        "objective add o_divorceLiquidSponge"
  e_so_d_SlorpGaming:         "objective add o_divorceSlorpGaming"
  e_so_d_omg_beebo:           "objective add o_divorceomg_beebo"
  e_so_d_whimsybun:           "objective add o_divorcewhimsybun"
  e_so_d_SmackDan:            "objective add o_divorceSmackDan"
  e_so_d_Blomstermoy:         "objective add o_divorceBlomstermoy"
  e_so_d_Haugland:            "objective add o_divorceHaugland"
  e_clear:                     "folder e_clear_m,e_clear_d"
  # Clear: Marry
  e_clear_m:                   "folder e_clear_m_1,e_clear_m_2"
  e_clear_m_1:                 "folder e_del_m_saspaa,e_del_m_PiT_MiN,e_del_m_BirgitP,e_del_m_tyloreo,e_del_m_bigbabie,e_del_m_lepicah,e_del_m_LiquidSponge"
  e_clear_m_2:                 "folder e_del_m_SlorpGaming,e_del_m_omg_beebo,e_del_m_whimsybun,e_del_m_SmackDan,e_del_m_Blomstermoy,e_del_m_Haugland"
  e_del_m_saspaa:              "objective remove o_marrysaspaa"
  e_del_m_PiT_MiN:             "objective remove o_marryPiT_MiN"
  e_del_m_BirgitP:             "objective remove o_marryBirgitP"
  e_del_m_tyloreo:             "objective remove o_marrytyloreo"
  e_del_m_bigbabie:            "objective remove o_marrybigbabie"
  e_del_m_lepicah:             "objective remove o_marrylepicah"
  e_del_m_LiquidSponge:        "objective remove o_marryLiquidSponge"
  e_del_m_SlorpGaming:         "objective remove o_marrySlorpGaming"
  e_del_m_omg_beebo:           "objective remove o_marryomg_beebo"
  e_del_m_whimsybun:           "objective remove o_marrywhimsybun"
  e_del_m_SmackDan:            "objective remove o_marrySmackDan"
  e_del_m_Blomstermoy:         "objective remove o_marryBlomstermoy"
  e_del_m_Haugland:            "objective remove o_marryHaugland"
  # Clear: Divorce
  e_clear_d:                   "folder e_clear_d_1,e_clear_d_2"
  e_clear_d_1:                 "folder e_del_d_saspaa,e_del_d_PiT_MiN,e_del_d_BirgitP,e_del_d_tyloreo,e_del_d_bigbabie,e_del_d_lepicah,e_del_d_LiquidSponge"
  e_clear_d_2:                 "folder e_del_d_SlorpGaming,e_del_d_omg_beebo,e_del_d_whimsybun,e_del_d_SmackDan,e_del_d_Blomstermoy,e_del_d_Haugland"
  e_del_d_saspaa:              "objective remove o_divorcesaspaa"
  e_del_d_PiT_MiN:             "objective remove o_divorcePiT_MiN"
  e_del_d_BirgitP:             "objective remove o_divorceBirgitP"
  e_del_d_tyloreo:             "objective remove o_divorcetyloreo"
  e_del_d_bigbabie:            "objective remove o_divorcebigbabie"
  e_del_d_lepicah:             "objective remove o_divorcelepicah"
  e_del_d_LiquidSponge:        "objective remove o_divorceLiquidSponge"
  e_del_d_SlorpGaming:         "objective remove o_divorceSlorpGaming"
  e_del_d_omg_beebo:           "objective remove o_divorceomg_beebo"
  e_del_d_whimsybun:           "objective remove o_divorcewhimsybun"
  e_del_d_SmackDan:            "objective remove o_divorceSmackDan"
  e_del_d_Blomstermoy:         "objective remove o_divorceBlomstermoy"
  e_del_d_Haugland:            "objective remove o_divorceHaugland"

  # When: Marry
  e_marrysaspaa:              "folder e_gtag_add_m_THIS,e_gtag_add_m_saspaa,e_notif_m_saspaa"
  e_marryPiT_MiN:             "folder e_gtag_add_m_THIS,e_gtag_add_m_PiT_MiN,e_notif_m_PiT_MiN"
  e_marryBirgitP:             "folder e_gtag_add_m_THIS,e_gtag_add_m_BirgitP,e_notif_m_BirgitP"
  e_marrytyloreo:             "folder e_gtag_add_m_THIS,e_gtag_add_m_tyloreo,e_notif_m_tyloreo"
  e_marrybigbabie:            "folder e_gtag_add_m_THIS,e_gtag_add_m_bigbabie,e_notif_m_bigbabie"
  e_marrylepicah:             "folder e_gtag_add_m_THIS,e_gtag_add_m_lepicah,e_notif_m_lepicah"
  e_marryLiquidSponge:        "folder e_gtag_add_m_THIS,e_gtag_add_m_LiquidSponge,e_notif_m_LiquidSponge"
  e_marrySlorpGaming:         "folder e_gtag_add_m_THIS,e_gtag_add_m_SlorpGaming,e_notif_m_SlorpGaming"
  e_marryomg_beebo:           "folder e_gtag_add_m_THIS,e_gtag_add_m_omg_beebo,e_notif_m_omg_beebo"
  e_marrywhimsybun:           "folder e_gtag_add_m_THIS,e_gtag_add_m_whimsybun,e_notif_m_whimsybun"
  e_marrySmackDan:            "folder e_gtag_add_m_THIS,e_gtag_add_m_SmackDan,e_notif_m_SmackDan"
  e_marryBlomstermoy:         "folder e_gtag_add_m_THIS,e_gtag_add_m_Blomstermoy,e_notif_m_Blomstermoy"
  e_marryHaugland:            "folder e_gtag_add_m_THIS,e_gtag_add_m_Haugland,e_notif_m_Haugland"
  # When: Divorce
  e_divorcesaspaa:            "folder e_gtag_del_m_THIS,g_gtag_del_m_saspaa,e_notif_d_saspaa"
  e_divorcePiT_MiN:           "folder e_gtag_del_m_THIS,g_gtag_del_m_PiT_MiN,e_notif_d_PiT_MiN"
  e_divorceBirgitP:           "folder e_gtag_del_m_THIS,g_gtag_del_m_BirgitP,e_notif_d_BirgitP"
  e_divorcetyloreo:           "folder e_gtag_del_m_THIS,g_gtag_del_m_tyloreo,e_notif_d_tyloreo"
  e_divorcebigbabie:          "folder e_gtag_del_m_THIS,g_gtag_del_m_bigbabie,e_notif_d_bigbabie"
  e_divorcelepicah:           "folder e_gtag_del_m_THIS,g_gtag_del_m_lepicah,e_notif_d_lepicah"
  e_divorceLiquidSponge:      "folder e_gtag_del_m_THIS,g_gtag_del_m_LiquidSponge,e_notif_d_LiquidSponge"
  e_divorceSlorpGaming:       "folder e_gtag_del_m_THIS,g_gtag_del_m_SlorpGaming,e_notif_d_SlorpGaming"
  e_divorceomg_beebo:         "folder e_gtag_del_m_THIS,g_gtag_del_m_omg_beebo,e_notif_d_omg_beebo"
  e_divorcewhimsybun:         "folder e_gtag_del_m_THIS,g_gtag_del_m_whimsybun,e_notif_d_whimsybun"
  e_divorceSmackDan:          "folder e_gtag_del_m_THIS,g_gtag_del_m_SmackDan,e_notif_d_SmackDan"
  e_divorceBlomstermoy:       "folder e_gtag_del_m_THIS,g_gtag_del_m_Blomstermoy,e_notif_d_Blomstermoy"
  e_divorceHaugland:          "folder e_gtag_del_m_THIS,g_gtag_del_m_Haugland,e_notif_d_Haugland"



  # Broadcast: Marry
  e_notif_m_saspaa:           "command broadcast &6%player% &2just touched saspaa with &4love&2.. they're now married"
  e_notif_m_PiT_MiN:          "command broadcast &6%player% &2just touched PiT_MiN with &4love&2.. they're now married"
  e_notif_m_BirgitP:          "command broadcast &6%player% &2just touched BirgitP with &4love&2.. they're now married"
  e_notif_m_tyloreo:          "command broadcast &6%player% &2just touched tyloreo with &4love&2.. they're now married"
  e_notif_m_bigbabie:         "command broadcast &6%player% &2just touched bigbabie with &4love&2.. they're now married"
  e_notif_m_lepicah:          "command broadcast &6%player% &2just touched lepicah with &4love&2.. they're now married"
  e_notif_m_LiquidSponge:     "command broadcast &6%player% &2just touched LiquidSponge with &4love&2.. they're now married"
  e_notif_m_SlorpGaming:      "command broadcast &6%player% &2just touched SlorpGaming with &4love&2.. they're now married"
  e_notif_m_omg_beebo:        "command broadcast &6%player% &2just touched omg_beebo with &4love&2.. they're now married"
  e_notif_m_whimsybun:        "command broadcast &6%player% &2just touched whimsybun with &4love&2.. they're now married"
  e_notif_m_SmackDan:         "command broadcast &6%player% &2just touched SmackDan with &4love&2.. they're now married"
  e_notif_m_Blomstermoy:      "command broadcast &6%player% &2just touched Blomstermoy with &4love&2.. they're now married"
  e_notif_m_Haugland:         "command broadcast &6%player% &2just touched Haugland with &4love&2.. they're now married"
  # Broadcast: Divorce
  e_notif_d_saspaa:           "command broadcast &6%player% &2just punched saspaa with &4hate&2.. they're now divorced"
  e_notif_d_PiT_MiN:          "command broadcast &6%player% &2just punched PiT_MiN with &4hate&2.. they're now divorced"
  e_notif_d_BirgitP:          "command broadcast &6%player% &2just punched BirgitP with &4hate&2.. they're now divorced"
  e_notif_d_tyloreo:          "command broadcast &6%player% &2just punched tyloreo with &4hate&2.. they're now divorced"
  e_notif_d_bigbabie:         "command broadcast &6%player% &2just punched bigbabie with &4hate&2.. they're now divorced"
  e_notif_d_lepicah:          "command broadcast &6%player% &2just punched lepicah with &4hate&2.. they're now divorced"
  e_notif_d_LiquidSponge:     "command broadcast &6%player% &2just punched LiquidSponge with &4hate&2.. they're now divorced"
  e_notif_d_SlorpGaming:      "command broadcast &6%player% &2just punched SlorpGaming with &4hate&2.. they're now divorced"
  e_notif_d_omg_beebo:        "command broadcast &6%player% &2just punched omg_beebo with &4hate&2.. they're now divorced"
  e_notif_d_whimsybun:        "command broadcast &6%player% &2just punched whimsybun with &4hate&2.. they're now divorced"
  e_notif_d_SmackDan:         "command broadcast &6%player% &2just punched SmackDan with &4hate&2.. they're now divorced"
  e_notif_d_Blomstermoy:      "command broadcast &6%player% &2just punched Blomstermoy with &4hate&2.. they're now divorced"
  e_notif_d_Haugland:         "command broadcast &6%player% &2just punched Haugland with &4hate&2.. they're now divorced"

  # Globaltag: Marry
  e_gtag_add_m_THIS:          "globaltag add married_%player%"
  e_gtag_add_m_saspaa:        "globaltag add married_saspaa"
  e_gtag_add_m_PiT_MiN:       "globaltag add married_PiT_MiN"
  e_gtag_add_m_BirgitP:       "globaltag add married_BirgitP"
  e_gtag_add_m_tyloreo:       "globaltag add married_tyloreo"
  e_gtag_add_m_bigbabie:      "globaltag add married_bigbabie"
  e_gtag_add_m_lepicah:       "globaltag add married_lepicah"
  e_gtag_add_m_LiquidSponge:  "globaltag add married_LiquidSponge"
  e_gtag_add_m_SlorpGaming:   "globaltag add married_SlorpGaming"
  e_gtag_add_m_omg_beebo:     "globaltag add married_omg_beebo"
  e_gtag_add_m_whimsybun:     "globaltag add married_whimsybun"
  e_gtag_add_m_SmackDan:      "globaltag add married_SmackDan"
  e_gtag_add_m_Blomstermoy:   "globaltag add married_Blomstermoy"
  e_gtag_add_m_Haugland:      "globaltag add married_Haugland"
  # Globaltag: Divorce
  e_gtag_del_m_THIS:          "globaltag del married_%player%"
  g_gtag_del_m_saspaa:        "globaltag del married_saspaa"
  g_gtag_del_m_PiT_MiN:       "globaltag del married_PiT_MiN"
  g_gtag_del_m_BirgitP:       "globaltag del married_BirgitP"
  g_gtag_del_m_tyloreo:       "globaltag del married_tyloreo"
  g_gtag_del_m_bigbabie:      "globaltag del married_bigbabie"
  g_gtag_del_m_lepicah:       "globaltag del married_lepicah"
  g_gtag_del_m_LiquidSponge:  "globaltag del married_LiquidSponge"
  g_gtag_del_m_SlorpGaming:   "globaltag del married_SlorpGaming"
  g_gtag_del_m_omg_beebo:     "globaltag del married_omg_beebo"
  g_gtag_del_m_whimsybun:     "globaltag del married_whimsybun"
  g_gtag_del_m_SmackDan:      "globaltag del married_SmackDan"
  g_gtag_del_m_Blomstermoy:   "globaltag del married_Blomstermoy"
  g_gtag_del_m_Haugland:      "globaltag del married_Haugland"

  #e_notifTouchedDova:     "command broadcast &6%player% &2just touched dova with &4love.. they're now married"
  #e_notifHitLeah:         "command broadcast &6%player% &2just punched lepicah with &4hate&r.. they're now divorced"


objectives:
  # Marry
  o_marrysaspaa:                  "interact right PLAYER 1 realname:saspaa conditions:!gchk_married_THIS,!gchk_married_saspaa events:e_marrysaspaa persistent"
  o_marryPiT_MiN:                 "interact right PLAYER 1 realname:PiT_MiN conditions:!gchk_married_THIS,!gchk_married_PiT_MiN events:e_marryPiT_MiN persistent"
  o_marryBirgitP:                 "interact right PLAYER 1 realname:BirgitP conditions:!gchk_married_THIS,!gchk_married_BirgitP events:e_marryBirgitP persistent"
  o_marrytyloreo:                 "interact right PLAYER 1 realname:tyloreo conditions:!gchk_married_THIS,!gchk_married_tyloreo events:e_marrytyloreo persistent"
  o_marrybigbabie:                "interact right PLAYER 1 realname:bigbabie conditions:!gchk_married_THIS,!gchk_married_bigbabie events:e_marrybigbabie persistent"
  o_marrylepicah:                 "interact right PLAYER 1 realname:lepicah conditions:!gchk_married_THIS,!gchk_married_lepicah events:e_marrylepicah persistent"
  o_marryLiquidSponge:            "interact right PLAYER 1 realname:LiquidSponge conditions:!gchk_married_THIS,!gchk_married_LiquidSponge events:e_marryLiquidSponge persistent"
  o_marrySlorpGaming:             "interact right PLAYER 1 realname:SlorpGaming conditions:!gchk_married_THIS,!gchk_married_SlorpGaming events:e_marrySlorpGaming persistent"
  o_marryomg_beebo:               "interact right PLAYER 1 realname:omg_beebo conditions:!gchk_married_THIS,!gchk_married_omg_beebo events:e_marryomg_beebo persistent"
  o_marrywhimsybun:               "interact right PLAYER 1 realname:whimsybun conditions:!gchk_married_THIS,!gchk_married_whimsybun events:e_marrywhimsybun persistent"
  o_marrySmackDan:                "interact right PLAYER 1 realname:SmackDan conditions:!gchk_married_THIS,!gchk_married_SmackDan events:e_marrySmackDan persistent"
  o_marryBlomstermoy:             "interact right PLAYER 1 realname:Blomstermoy conditions:!gchk_married_THIS,!gchk_married_Blomstermoy events:e_marryBlomstermoy persistent"
  o_marryHaugland:                "interact right PLAYER 1 realname:Haugland conditions:!gchk_married_THIS,!gchk_married_Haugland events:e_marryHaugland persistent"
  # Divorce
  o_divorcesaspaa:                "interact left PLAYER 1 realname:saspaa conditions:gchk_married_THIS,gchk_married_saspaa events:e_divorcesaspaa persistent"
  o_divorcePiT_MiN:               "interact left PLAYER 1 realname:PiT_MiN conditions:gchk_married_THIS,gchk_married_PiT_MiN events:e_divorcePiT_MiN persistent"
  o_divorceBirgitP:               "interact left PLAYER 1 realname:BirgitP conditions:gchk_married_THIS,gchk_married_BirgitP events:e_divorceBirgitP persistent"
  o_divorcetyloreo:               "interact left PLAYER 1 realname:tyloreo conditions:gchk_married_THIS,gchk_married_tyloreo events:e_divorcetyloreo persistent"
  o_divorcebigbabie:              "interact left PLAYER 1 realname:bigbabie conditions:gchk_married_THIS,gchk_married_bigbabie events:e_divorcebigbabie persistent"
  o_divorcelepicah:               "interact left PLAYER 1 realname:lepicah conditions:gchk_married_THIS,gchk_married_lepicah events:e_divorcelepicah persistent"
  o_divorceLiquidSponge:          "interact left PLAYER 1 realname:LiquidSponge conditions:gchk_married_THIS,gchk_married_LiquidSponge events:e_divorceLiquidSponge persistent"
  o_divorceSlorpGaming:           "interact left PLAYER 1 realname:SlorpGaming conditions:gchk_married_THIS,gchk_married_SlorpGaming events:e_divorceSlorpGaming persistent"
  o_divorceomg_beebo:             "interact left PLAYER 1 realname:omg_beebo conditions:gchk_married_THIS,gchk_married_omg_beebo events:e_divorceomg_beebo persistent"
  o_divorcewhimsybun:             "interact left PLAYER 1 realname:whimsybun conditions:gchk_married_THIS,gchk_married_whimsybun events:e_divorcewhimsybun persistent"
  o_divorceSmackDan:              "interact left PLAYER 1 realname:SmackDan conditions:gchk_married_THIS,gchk_married_SmackDan events:e_divorceSmackDan persistent"
  o_divorceBlomstermoy:           "interact left PLAYER 1 realname:Blomstermoy conditions:gchk_married_THIS,gchk_married_Blomstermoy events:e_divorceBlomstermoy persistent"
  o_divorceHaugland:              "interact left PLAYER 1 realname:Haugland conditions:gchk_married_THIS,gchk_married_Haugland events:e_divorceHaugland persistent"


conditions:
  gchk_married_THIS:              "globaltag married_%player%"
  gchk_married_saspaa:            "globaltag married_saspaa"
  gchk_married_PiT_MiN:           "globaltag married_PiT_MiN"
  gchk_married_BirgitP:           "globaltag married_BirgitP"
  gchk_married_tyloreo:           "globaltag married_tyloreo"
  gchk_married_bigbabie:          "globaltag married_bigbabie"
  gchk_married_lepicah:           "globaltag married_lepicah"
  gchk_married_LiquidSponge:      "globaltag married_LiquidSponge"
  gchk_married_SlorpGaming:       "globaltag married_SlorpGaming"
  gchk_married_omg_beebo:         "globaltag married_omg_beebo"
  gchk_married_whimsybun:         "globaltag married_whimsybun"
  gchk_married_SmackDan:          "globaltag married_SmackDan"
  gchk_married_Blomstermoy:       "globaltag married_Blomstermoy"
  gchk_married_Haugland:          "globaltag married_Haugland"