npcs:
  '71':   "mrloot"

conversations:
  mrloot:
    quester: "Mr. Loot"
    first: alreadyLooted,giveloot

    NPC_options:
      # Giving loot
      giveloot:
        conditions: "!chk_gotLoot"
        text: "As we ascend a mountain, we realize that the summit is not the only reward—the growth, strength, and self-discovery along the way are equally valuable.\n\nYou have earned your reward."
        pointer: getreward
      rewardlist:
        text: "1x  Potion of Slow Falling (4:00)\n64x Bottle o' Enchanting\n1x  Diamond Ore\n2x  Frogspawn\n1x  Dungeon Token"
        event: e_CompleteDungeon
        #exit

      # Already looted
      alreadyLooted:
        conditions: "chk_gotLoot"
        text: "You already got your share!"
        #exit


    player_options:
      # Giving loot
      getreward:
        text: "..."
        pointer: rewardlist


events:
  # Give reward
  e_CompleteDungeon:        "folder e_text_DungeonComplete,e_text_DungeonComplete_2,tag_add_looted,chat_DungeonComplete,e_loot,e_addScore"
  e_text_DungeonComplete:   "notify &aDungeon Complete\n&aSky io:title"
  e_text_DungeonComplete_2: "notify &aSky_Dungeon io:advancement frame:challenge icon:diamond"
  tag_add_looted:           "tag add SD_Looted"
  chat_DungeonComplete:     "command broadcast &6%player% &2completed the Sky Dungeon"
  e_loot:                   "give i_potion:1,i_expBtl:64,i_diamond_ore:1,i_frogspawn:2,i_DungeonToken"
  e_addScore:               "score quests 1 action:add"


conditions:
  chk_gotLoot:              "tag SD_Looted"


items:
  i_potion:                 "minecraft:potion type:SLOW_FALLING extended"
  i_expBtl:                 "minecraft:experience_bottle"
  i_diamond_ore:            "minecraft:deepslate_diamond_ore"
  i_frogspawn:              "minecraft:frogspawn"
  i_DungeonToken:           "minecraft:sunflower name:&6#11_Sky_Dungeon lore:&5Dungeon_Token enchants:DURABILITY:1 flags:HIDE_ENCHANTS"